<a href="https://colab.research.google.com/github/hanarifdahs/hacktiv8/blob/main/h8dsft_Linear_Algebra2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Soal 1

In [17]:
import numpy as np

In [18]:
tensor = np.array([
                    [[23,50],[7,12]],
                    [[57,67],[99,43]],
                    [[75,21],[57,12]],
                    [[87,26],[18,84]]
                  ])
print(tensor)

[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


#Soal 2

In [19]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([[17],[22],[19]])
print(A)
print(B)

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]]
[[17]
 [22]
 [19]]


In [20]:

print(A*B)

[[ 391  850  323]
 [ 154  264 2398]
 [1083 1273 1862]]


#Soal 3

In [21]:
from numpy.linalg import det
from numpy.linalg import inv

In [22]:
A

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [26]:
A.T # Transpose

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [24]:
det(A) #to find determinant

131344.0000000002

In [25]:
inv(A) #to find inverse

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])